[workspace]
members = [
    "cli",
    "core",
    "compiler",

    "packages/typst.ts",

    "exporter/ws",

    "contrib/fontctl",
]

[patch.crates-io]
typst-ts-core = { path = "core" }
typst-ts-compiler = { path = "compiler" }

typst = { git = "https://github.com/Myriad-Dreamin/typst.git", branch = "typst.ts" }
typst-library = { git = "https://github.com/Myriad-Dreamin/typst.git", branch = "typst.ts" }

# typst = { path = "../typst" }
# typst-library = { path = "../typst/library" }

[profile.release]
opt-level = 3
debug = true
lto = "thin"
