[workspace]
members = [
    "cli",
    "core",
    "compiler",

    "packages/typst.ts",

    "exporter/ws",

    "contrib/fontctl",
]

[patch.crates-io]
typst-ts-core = { path = "core" }
typst-ts-compiler = { path = "compiler" }

[profile.release]
opt-level = 3
debug = true
lto = "thin"
