[package]
name = "typst-renderer-ts"
version = "0.1.3"
license = "Apache-2.0"
edition = "2021"
readme = "README.md"
description = "Render Typst documents in browser."
repository = "https://github.com/Myriad-Dreamin/typst.ts"

[lib]
crate-type = ["cdylib"]

[dependencies]
typst-ts-core = "0.1.3"
typst-ts-canvas-exporter = "0.1.3"

typst = "0.2.0"
typst-library = "0.2.0"
comemo = "0.2"

once_cell = "1.17.1"
siphasher = "0.3.10"
elsa = "1.8.0"

pollster = "0.3.0"
tiny-skia = "0.6.6"

serde_json = { version = "1.0.95", optional = true }
serde = { version = "1.0.119", optional = true }
rmp-serde = { version = "1.1.1", optional = true }

# Everything to do with wasm
wasm-bindgen = { version = "^0.2" }
js-sys = "^0.3"
wasm-bindgen-futures = "^0.4"
serde-wasm-bindgen = "^0.5"
web-sys = { version = "^0.3", features = ["console", "Window", "Blob", "ImageData"] }

[dev-dependencies]
wasm-bindgen-test = "0.3.0"
typst-renderer-ts = { path = ".", features = ["serde_json", "serde_rmp"] }
web-sys = { version = "^0.3", features = ["console", "Performance", "PerformanceTiming", "Window", "Blob", "ImageData"] }

[features]
serde_json = ["dep:serde_json"]
serde_rmp = ["dep:serde", "dep:rmp-serde"]
default = []
