[package]
name = "typst-ts-cli"
version = "0.1.6"
license = "Apache-2.0"
edition = "2021"
description = "Command line tool for Typst.ts."
repository = "https://github.com/Myriad-Dreamin/typst.ts"

[dependencies]
typst = "0.3.0"
typst-library = "0.3.0"

typst-ts-core = "0.1.6"
typst-ts-compiler = "0.1.6"

typst-ts-pdf-exporter = { version = "0.1", optional = true }
typst-ts-raster-exporter = { version = "0.1", optional = true }
typst-ts-serde-exporter = { version = "0.1", optional = true }
# typst-ts-ws-exporter = { version = "0.1", optional = true }

codespan-reporting = "0.11"

clap = { version = "4.2", features = ["derive", "env", "unicode", "wrap_help"] }
clap_complete = "4.2"
clap_complete_fig = "4.2"

tokio = {version = "1.27.0", features = ["full"]}

serde = "1.0.159"
serde_json = "1.0.95"
rmp-serde = { version = "1.1.1" }

[features]
pdf = ["typst-ts-pdf-exporter"]
raster = ["typst-ts-raster-exporter"]
serde-json = ["typst-ts-serde-exporter", "typst-ts-serde-exporter/json"]
serde-rmp = ["typst-ts-serde-exporter", "typst-ts-serde-exporter/rmp"]
default = ["pdf", "raster", "serde-json", "serde-rmp"]
