[package]
name = "typst-ts-core"
version = "0.1.3"
license = "Apache-2.0"
edition = "2021"
description = "Serialize Typst document tree."
repository = "https://github.com/Myriad-Dreamin/typst.ts"

[dependencies]
typst = "0.2.0"
typst-library = "0.2.0"
comemo = "0.2"
siphasher = "0.3.10"

once_cell = "1.17.1"

serde = "1.0.159"
serde_json = "1.0.95"
