[package]
name = "typst-ts-core"
version = "0.1.0"
license = "Apache-2.0"
edition = "2021"
description = "Serialize Typst document tree."
repository = "https://github.com/Myriad-Dreamin/typst.ts"

[dependencies]
typst = { git = "https://github.com/typst/typst.git" }
typst-library = { git = "https://github.com/typst/typst.git" }
comemo = "0.2"
siphasher = "0.3.10"

serde = "1.0.159"
serde_json = "1.0.95"
