[package]
name = "typst-ts-canvas-exporter"
version = "0.1.6"
license = "Apache-2.0"
edition = "2021"
description = "Export a frame of Typst document into canvas element."
repository = "https://github.com/Myriad-Dreamin/typst.ts"

[dependencies]

typst-ts-core = "0.1"

typst = "0.3.0"
comemo = "0.2"

tiny-skia = "0.9.0"
ttf-parser = "0.18.1"
flate2 = "1"
data-url = "0.2.0"

wasm-bindgen = { version = "^0.2" }
js-sys = "^0.3"
web-sys = { version = "^0.3", features = ["console", "CanvasRenderingContext2d", "Path2d", "Blob", "ImageData", "HtmlImageElement", "HtmlElement", "Url", "BlobPropertyBag"] }
