[package]
name = "typst-ts-raster-exporter"
version = "0.1.6"
license = "Apache-2.0"
edition = "2021"
description = "Export a frame of Typst document into a raster image."
repository = "https://github.com/Myriad-Dreamin/typst.ts"

[dependencies]

typst = "0.3.0"
comemo = "0.2"

image = { version = "0.24", default-features = false, features = ["png", "jpeg", "gif"] }
usvg = { version = "0.32", default-features = false, features = ["text"] }
tiny-skia = "0.9.0"
ttf-parser = "0.18.1"
roxmltree = "0.18"
bytemuck = "1"
pixglyph = "0.1"
flate2 = "1"
resvg = { version = "0.32", default-features = false }
