name: typst_ts::ci
on: [push, pull_request]

env:
  RUSTFLAGS: '-Dwarnings'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Download Repo
        uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install Artifact Cache
        uses: Swatinem/rust-cache@v2
      - name: Prepare fonts
        run: cargo run --bin typst-ts-fontctl
      - name: Fmt check
        run: cargo fmt --check --all
      # todo: clippy tests
      # - name: Clippy check
      #   run: cargo clippy --workspace --all-targets
      - name: Prepare artifacts
        run: cargo run --bin typst-ts-cli -- compile --workspace fuzzers/corpora/math/ --entry fuzzers/corpora/math/main.typ
      - name: Build
        run: cargo build --workspace
      - name: Test
        run: cargo test --workspace --no-fail-fast
